Major improvements to init subsystem
This commit MUST be released to both `beta` and `prod` AT THE SAME TIME.
(Otherwise the `beta` instance of the site will probably get b0rked
pretty hard from the init files being desync'ed.)

I normally wouldn't want to mess with the init subsystem, but getting
PHPStan working definitely required me to do so!

And, while this commit is largely motivated by getting PHPStan
working with the project, it has branched into a few other things too.

Here are some of the bigger points:
* Fewer .php files in the Kickback (namespace root) folder. (Good!)
* There are more initscripts now, but they are consolidated into
  the `html/Kickback/InitializationScripts` folder.
* A single `init.php` file is left in `html/Kickback` for ease of use,
  with the added benefit of not requiring existing code to be refactored.
* Less init code is executed in the (potentially) wrong SCRIPT_ROOT
  in environs with multiple roots (ex: `beta` vs `prod`).
* There is now an `init_for_phpstan.php` entry point that can be used
  to inform the init system that it is being executed by PHPStan.
* Optional tracing of call/return/throw and activity for autoloader
  functions.
* Also there is now a basic tracing module for use in the init
  subsystem, though it's mostly just for the autoloader right now.
* Autoloader bugfix that is a workaround for `scandir`/`readdir`
  behavior that resulted in infinite loops or OOM.
* When executed from PHPStan, the autoloader will no longer throw
  exceptions when classes fail to autoload.
* Autoloader (and init's tracing functions) will switch from `echo` to
  `error_log` when running in website context, for improved security.
* The entire init system has now been swept by PHPStan, and it now
  produces zero errors.

The `scandir`/`readdir` workaround fixes this error:
```
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 158267867136 bytes) (tried to allocate 4096 bytes) in /var/www/localhost/kickback-kingdom-website/html/Kickback/autoload_classes.php on line 159
Fatal error: Out of memory (allocated 158267867136 bytes) (tried to allocate 4096 bytes) in /var/www/localhost/kickback-kingdom-website/html/Kickback/autoload_classes.php on line 159
```
(This particular reading was from PHPStan using the autoloader in an
attempt to load the `html/Kickback/Utilities/FormToken.php` class.
Yeah, it used >150GB in a single thread before giving up.)

This commit will not contain the composer changes or PHPStan config that
was necessary to run it on this project. This commit is already bulky
enough, and I don't want to change more than this on `prod` (because
this commit has the unusual property of requiring synchronized release,
but the PHPStan stuff doesn't), so I'll commit the rest of the PHPStan
integration in a later commit.